### PR TITLE
Use different color for online/offline sessions

### PR DESCRIPTION
**Pull request by developStorm**

### CODE REVIEW

**Comment by developStorm** [comment]
@Rsl1122 👋🏻 Did you notice there is a PR?

**Comment by Rsl1122** [comment]
Yes, I think white doesn't work as a color here, maybe the background color in use should be altered slightly instead?

**Comment by developStorm** [comment]
White actually works well with the current background color (#F8F9FC) on my side! 
image

**Comment by Rsl1122** [comment]
Does it work with night mode enabled? 🤔

**Comment by developStorm** [comment]
Good catch... It's not. We can perhaps have a check for night mode. The default color performs great with dark mode.

**Comment by developStorm** [comment]
I don't think there is a method for me to get current theme. Do you have any suggestion?

**Comment by Rsl1122** [comment]
A special case in the night mode stylesheet might work
<https://github.com/plan-player-analytics/Plan/blob/master/Plan/common/src/main/resources/assets/plan/web/js/color-selector.js#L165>

**Comment by developStorm** [comment]
Should be good with night mode now 😃

**Comment by Rsl1122** [comment]
I still think that the difference between the online and offline background color is too drastic.
The color difference will make the sessions on the list appear as two different groups of sessions when the online sessions are essentially the same, but in progress. (https://en.wikipedia.org/wiki/Principles_of_grouping#Similarity)

**Comment by developStorm** [comment]
I think they should be grouped differently since this helps us identify which sessions are on going and which are done. Have a whole green block is not making sense for me because usually when some blocks are colored, that means the developer wants to emphasize this part. However in this case all elements are emphasized.

**Comment by Rsl1122** [comment]
That makes sense.
You got me thinking. The original reasoning for the color is to tie the teal color to the other statistics on the page with sessions (all session related stuff is colorcoded teal), but outlined items would work much better (eg, a teal outline with whatever background the table is using), this way the online items could be highlighted without making the finished sessions non-colorcoded.

Unfortunately there is no a css for outlined colors yet, so that's something to add.
Would you like to give it a shot or should I merge this?

**Comment by developStorm** [comment]
Outline sounds nice! However I'm not very familiar with css so unfortunately I may not be able to implement that...

**Comment by Rsl1122** [comment]
Alright I'll just merge this one then.

**Pull request merged**
