### PR TITLE
Update to 1.20.5

### PR DESCRIPTION
**Pull request by DrexHD**
### Your checklist for this pull request
🚨 Please review the [guidelines for contributing](https://github.com/plan-player-analytics/Plan/blob/master/CONTRIBUTING.md#writing-a-good-pull-request) to this repository.

- [x] Make sure your name is added to Contributors file `/Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java`
- [x] If PR:ing locale changes also add a LangCode with your name `/Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java`

### Description
This draft PR is intended to track the progress of updating this mod _(fabric module)_ to 1.20.5

Thank you!

### CODE REVIEW

**Comment by AuroraLS3** [comment]
Awesome!

**Comment by DrexHD** [comment]
This has now been ported to 1.20.5-rc2 and is ready for review. No further changes are expected for 1.20.5!

1.20.5 bumped the Java version used by Minecraft from 17 to 21, this PR reflects that change. This doesn't seem to cause any problems in the project.

**Review by AuroraLS3 — APPROVED** [review]
Looks good! Could you change jitpack.yml to install JDK 21, I think it's using 20 atm

**Comment by AuroraLS3** [comment]
I'll merge this since it fixes a build issue with 0.3-SNAPSHOT of fabric permissions api

**Pull request merged**
