### PR TITLE
Pull

### PR DESCRIPTION
**Pull request by WolverStones**
### Your checklist for this pull request
🚨 Please review the [guidelines for contributing](https://github.com/plan-player-analytics/Plan/blob/master/CONTRIBUTING.md#writing-a-good-pull-request) to this repository.

- [ ] Make sure your name is added to Contributors file `/Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java`
- [ ] If PR:ing locale changes also add a LangCode with your name `/Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java`

### Description
Please describe your pull request.

Thank you!

### CODE REVIEW

**Comment by AuroraLS3** [comment]
Is this to update locale_CS? :)

**Comment by WolverStones** [comment]
Sorry my bad

**Comment by AuroraLS3** [comment]
You can fix this by copying the locale file, deleting the fork (repository settings > danger zone), re-forking and then applying the changes to the locale file :)

**Comment by AuroraLS3** [comment]
I have applied the changes to locale_CS.txt :)

**Pull request closed without merging**
