### PR TITLE
Started translation into Dutch.

### PR DESCRIPTION
**Pull request by jvdoorn**

### CODE REVIEW

**Comment by Rsl1122** [comment]
Lemme know when you want this PR merged :)

**Comment by Argetan** [comment]
You can merge it now or wait till I'm done with them all, doesn't really matter to me, to be honest 😃

**Comment by Rsl1122** [comment]
How's it going? :)

**Comment by Argetan** [comment]
Slowly translating things, a lot of things sound so stupid in Dutch though 🤣

**Comment by Rsl1122** [comment]
Imma close this PR, let me know if you want to continue to work on this and I'll reopen it.

**Pull request closed without merging**
