### PR TITLE
Append version string to all resource URLs

### PR DESCRIPTION
**Pull request by KairuByte**
### Your checklist for this pull request
🚨 Please review the [guidelines for contributing](https://github.com/plan-player-analytics/Plan/blob/master/CONTRIBUTING.md#writing-a-good-pull-request) to this repository.

- [x] Make sure your name is added to Contributors file `/Plan/common/src/main/java/com/djrapitops/plan/delivery/rendering/html/Contributors.java`
- [x] If PR:ing locale changes also add a LangCode with your name `/Plan/common/src/main/java/com/djrapitops/plan/settings/locale/LangCode.java`

### Description
- Rename existing `version` placeholder to `versionButton`.
- Repurpose existing `version` placeholder to output current version and build number.
- Append `?v={version}` to the end of local resources.

Thank you!

### CODE REVIEW

**Review by AuroraLS3 — APPROVED** [review]
Thank you for such a well made PR.

Sorry to bring this up after you've already done so much work, but I'm a bit uncertain about the necessity for this change, since the issue that prompted the work was ultimately caused by old html customization file rather than cloudflare cache (although it did mask the issue).

While cloudflare is used by few people, the issue with the cache is not limited to only the static resources, since the cache might store the html and other data that isn't timestamped as well - it should be disabled regardless.

This change could make it less apparent to users that something is broken because of a cache - as everything seems to load fine but some data is outdated or doesn't update for some reason - and make people less likely to look for a solution.

I'll leave this open for now to consider further - no need to address the comments.

What do you think? :)

**Comment by KairuByte** [comment]
I'm actually not certain how much this would help with Cloudflare caching to be honest, as you mentioned they cache the entire page along with the resources. This is more a solution for browser caching, which can hold on to old resources indefinitely.

The common fix of clearing your cache after an update is absolutely one of the solutions that works, but there is an inherent issue when end users who are *not* a server owner, nor tech savvy, do not know of said solution.

**Comment by Kopo942** [comment]
Added note: Cloudflare does _not_ cache HTML pages by default (since they might change based on different characteristics), only static resources; this is inherently what makes webpack's (& other resource bundlers') filename versioning to work. Caching HTML pages can be added as a custom page rule, but I doubt a regular Plan user would ever do that.

**Comment by AuroraLS3** [comment]
> This is more a solution for browser caching, which can hold on to old resources indefinitely.

Since Plan doesn't send cache expire headers none of the Plan resources are cached by browser by default, and are only cached if cloudflare cache is enabled.

I wasn't aware about cloudflare not caching html, thanks for the correction.

> there is an inherent issue when end users who are not a server owner, nor tech savvy, do not know of said solution.

This is a good argument, and I think this PR might be beneficial for those users.

----

> I've been thinking about including Node & webpack in our build system for quite a while now (since Plan is after all quite a web-heavy project) to enable versioning, automatic dependency handling & bundling of web files, but

I get the appeal, but re-creating the frontend has been a massive refactoring in the past, and that's something I don't personally really have that much time for anymore. I could make the argument that html customization would go out the window with react, but that part of the plugin is rather unforgiving already so I'm unsure how many actually use it (no data).

So rewriting frontend with react has two outcomes: One where html customization is not possible so some people don't update, and some people demand their customization back (and less people know react than bare html, so that's a rather difficult problem) - or I end up with two frontends to maintain and that latter option I really can't do. I can try do a poll and add a bstats metric for html customization to see if it actually used.

**Comment by Kopo942** [comment]
> So rewriting frontend with react has two outcomes

Ah, I guess you mixed up my comments here and on Discord 😅 the React rewrite was just a silly throw (that I still might give a go on my spare time), but the comment above about adding Node & webpack into the build system was the actual thing I've been thinking about!

**Review by AuroraLS3 — APPROVED** [review]

**Pull request merged**
